site_name: Take Notes With Me
site_url: http://yankunqiu.me
repo_url: https://github.com/MarcosQiu/my-docs
repo_name: MarcosQiu/my-docs
theme:
  name: material
  favicon: images/critical-thinking.gif
  logo: images/brain.png
  icon:
    repo: fontawesome/brands/github-alt
  plugins:
  - search:
      lang:
        - en
  features:
    - navigation.top
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
generator: false
copyright: Copyright &copy; 2021 Yankun Qiu
extra:
  disqus: mydocs-2
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yankunqiu/
    - icon: fontawesome/brands/github
      link: https://github.com/MarcosQiu
    - icon: fontawesome/solid/paper-plane
      link: mailto:hola@yankunqiu.me
